version: '3.4'

services:
  frontend:
    build:
      context: frontend
    depends_on:
      - api
    command: sh -c "yarn && yarn dev"
    environment:
      - API_PROXY_BASE=http://api:8000
      - NUXT_HOST=0.0.0.0
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
  
  api:
    build:
      context: api
    command: sh -c "pipenv install && python api.py"
    volumes:
      - ./api:/app

volumes:
  node_modules: