# cd frontend
# yarn generate
# cd ..
# docker-compose -f docker-compose.nginx.yml up

version: '3.4'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - 3001:80

  api:
    build:
      context: api
    command: sh -c "pipenv install && python api.py"
    environment:
      - DEBUG=1
    volumes:
      - ./api:/app